version: '3.9'

services:
  mongo:
    image: mongo
    container_name: discoding-mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: test
    ports:
      - 29017:27017
    volumes:
      - ./data:/data/db